### ISSUE TITLE
Meet some issues while running neutrino in sgalng inference engine

### ISSUE THREAD

**Issue by shishisizhu** [open-neutrino/neutrino#13]
When I run "neutrino -p ~/neutrino/neutrino/tools/block_sched.py python3 -m sglang.launch_server ......" command to start slang inference servce, I meet some problems as below( It's right when I just run common start command ). Did you use to meet such problem? Can you help me ?

[info] 1753966468185832704 cublas use real:  0x784d65ad02e0 2
[2025-07-31 12:54:28] Scheduler hit an exception: Traceback (most recent call last):
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 2986, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, pp_rank, dp_rank)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 346, in __init__
    self.tp_worker = TpWorkerClass(
                     ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 66, in __init__
    self.worker = TpModelWorker(
                  ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 82, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 233, in __init__
    self.initialize(min_per_gpu_memory)
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 328, in initialize
    self.init_cublas()
  File "/root/miniconda3/envs/pytorch/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 1303, in init_cublas
    c = a @ b
        ~~^~~
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

[2025-07-31 12:54:28] Received sigquit from a child process. It usually means the child failed.

**Comment by shishisizhu** [comment]
By the way, some ignorant errors occur as below(commonly running sglang is OK). There are some problems in dlsym ? It' takes me some time to deal with it. Sincerely hope that you can help me !!!  

[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.clip. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.deepseek_janus_pro. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.gemma3_mm. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.idefics2. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.interns1. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.internvl. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.minicpmo. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.minicpmv. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.mllama. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.phi4mm. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.pixtral. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.qwen2_5_vl. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.qwen2_audio. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.qwen2_vl. Can not import sgl_kernel. Please check your installation.
[dlopen] /root/miniconda3/envs/pytorch/lib/python3.11/site-packages/neutrino/build/libcuda.so.1 : 258, 0x3adb58e0
[2025-07-31 12:53:39] Ignore import error when loading sglang.srt.models.siglip. Can not import sgl_kernel. Please check your installation.

**Comment by huangs0** [comment]
[Neutrino cannot supporting cuBLAS](https://open-neutrino.github.io/docs/software-support#cublascudnn) for technical (`cuBLAS` uses [dark apis](https://news.ycombinator.com/item?id=39346108) and will self-check if being hooked), and legal reasons (cuBLAS has stricter EULA than normal CUDA code). 

But Neutrino shall apply enough masking over cuBLAS (in `preload.c`) so it can run with PyTorch (whose `@` uses cuBLAS). And I found the source code of `init_cublas()` as follows:

```py
def init_cublas(): # I removed self as we are not in the class
        """We need to run a small matmul to init cublas. Otherwise, it will raise some errors later."""
        dtype = torch.float16
        device = "cuda"
        a = torch.ones((16, 16), dtype=dtype, device=device)
        b = torch.ones((16, 16), dtype=dtype, device=device)
        c = a @ b
        return c
```

I run the code and found no error (just cuBLAS kernel not recorded). Could you please try to run it separately and see if there is any issues. This can help me classify the problem from your environment or others (`neutrino`/`sglang`).

Moreover, `cuBLAS` and `sgl_kernel` problem shall be handled by `preload.c`. If there's certain error, could you please try to compile `neutrino` with macro `DL_VERBOSE`?

**Comment by shishisizhu** [comment]
Thanks for your reply @huangs0 !  It seems the error is caused by setproctitle.setproctitle(...).  Below is a sample program to illustrate the issue:
`
import setproctitle
import multiprocessing as mp
import torch
import os
import sys

def run_cublas():
    a = torch.randn(4, 4, device='cuda')
    b = torch.randn(4, 4, device='cuda')
    try:
        c = a @ b
        print(f"[pid] {os.getpid()}")
        print(c)
        sys.stdout.flush()
        return True
    except Exception as e:
        print(f"[PID]: {os.getpid()} Error: {e}")
        sys.stdout.flush()
        return False

def process_run(queue):
    #run_cublas() //It would be right if you run cublas before setproctitle. 
    setproctitle.setproctitle(f"test_process_{os.getpid()}")
    print(f"[pid] {os.getpid()} before run cublas")
    success = run_cublas()
    print(f"[pid] {os.getpid()} after run cublas")
    queue.put({'pid': os.getpid(), 'success': success})

if __name__ == "__main__":
    mp.set_start_method('spawn')
    result_queue = mp.Queue()
    processes = []
    run_cublas()
    for i in range(2):
        p = mp.Process(target=process_run, args=(result_queue,))
        p.start()
        processes.append(p)
    for p in processes:
        p.join()
    print("\n" + "="*50)
    print("Exit information:")
    for i, p in enumerate(processes):
        print(f"Process {i+1} (PID: {p.pid}) exited with code {p.exitcode}")
    print("\nExecution results:")
    while not result_queue.empty():
        res = result_queue.get()
        status = "Success" if res['success'] else "Failed"
        print(f"PID {res['pid']}: {status}")
`
I experienced a similar error while running the command `neutrino -p xxx python3 test_cublas.py`. Interestingly, running `python3 test_cublas.py` on its own works without any issues. I would truly appreciate your help in resolving this problem.

**Comment by shishisizhu** [comment]
Thanks for your reply @huangs0  ! It seems the error is caused by setproctitle.setproctitle(...). Below is a sample program to illustrate the issue:

```
import setproctitle
import multiprocessing as mp
import torch
import os
import sys

def run_cublas():
    a = torch.randn(4, 4, device='cuda')
    b = torch.randn(4, 4, device='cuda')
    try:
        c = a @ b
        print(f"[pid] {os.getpid()}")
        print(c)
        sys.stdout.flush()
        return True
    except Exception as e:
        print(f"[PID]: {os.getpid()} Error: {e}")
        sys.stdout.flush()
        return False

def process_run(queue):
    #run_cublas() //It would be right if you run cublas before setproctitle. 
    setproctitle.setproctitle(f"test_process_{os.getpid()}")
    print(f"[pid] {os.getpid()} before run cublas")
    success = run_cublas()
    print(f"[pid] {os.getpid()} after run cublas")
    queue.put({'pid': os.getpid(), 'success': success})

if __name__ == "__main__":
    mp.set_start_method('spawn')
    result_queue = mp.Queue()
    processes = []
    run_cublas()
    for i in range(2):
        p = mp.Process(target=process_run, args=(result_queue,))
        p.start()
        processes.append(p)
    for p in processes:
        p.join()
    print("\n" + "="*50)
    print("Exit information:")
    for i, p in enumerate(processes):
        print(f"Process {i+1} (PID: {p.pid}) exited with code {p.exitcode}")
    print("\nExecution results:")
    while not result_queue.empty():
        res = result_queue.get()
        status = "Success" if res['success'] else "Failed"
        print(f"PID {res['pid']}: {status}")
```

I experienced a similar error while running the command `neutrino -p xxx python3 test_cublas.py`. Interestingly, running `python3 test_cublas.py` on its own works without any issues. I would truly appreciate your help in resolving this problem.

**Comment by shishisizhu** [comment]
Thanks for your reply @huangs0 ! It seems the error is caused by setproctitle.setproctitle(...). Below is a sample program to illustrate the issue:

```
import setproctitle
import multiprocessing as mp
import torch
import os
import sys

def run_cublas():
    a = torch.randn(4, 4, device='cuda')
    b = torch.randn(4, 4, device='cuda')
    try:
        c = a @ b
        print(f"[pid] {os.getpid()}")
        print(c)
        sys.stdout.flush()
        return True
    except Exception as e:
        print(f"[PID]: {os.getpid()} Error: {e}")
        sys.stdout.flush()
        return False

def process_run(queue):
    #run_cublas() //It would be right if you run cublas before setproctitle. 
    setproctitle.setproctitle(f"test_process_{os.getpid()}")
    print(f"[pid] {os.getpid()} before run cublas")
    success = run_cublas()
    print(f"[pid] {os.getpid()} after run cublas")
    queue.put({'pid': os.getpid(), 'success': success})

if __name__ == "__main__":
    mp.set_start_method('spawn')
    result_queue = mp.Queue()
    processes = []
    run_cublas()
    for i in range(2):
        p = mp.Process(target=process_run, args=(result_queue,))
        p.start()
        processes.append(p)
    for p in processes:
        p.join()
    print("\n" + "="*50)
    print("Exit information:")
    for i, p in enumerate(processes):
        print(f"Process {i+1} (PID: {p.pid}) exited with code {p.exitcode}")
    print("\nExecution results:")
    while not result_queue.empty():
        res = result_queue.get()
        status = "Success" if res['success'] else "Failed"
        print(f"PID {res['pid']}: {status}")
```

I experienced a similar error while running the command `neutrino -p xxx python3 test_cublas.py`. However, running `python3 test_cublas.py` on its own works without any issues. I would truly appreciate your help in resolving this problem.

**Comment by huangs0** [comment]
So if you don't call `setproctitle`, then everything will be fine? 

This is quite weird but interesting.

**Comment by shishisizhu** [comment]
I resolved the "CUDA error: CUBLAS_STATUS_NOT_INITIALIZED" issue by adjusting the position of `init_cublas`, but additional errors have occurred in `neutrino sglang`

**Comment by shishisizhu** [comment]
When I removed `setproctitle.setproctitle`, the server seemed to start successfully. It's so weird!

**Comment by shishisizhu** [comment]
The` setproctitle.setproctitle `function modifies the environment variables, clearing them out.
