### ISSUE TITLE
Is WSL supported?

### ISSUE THREAD

**Issue by JLabandon** [open-neutrino/neutrino#2]
I'm using WSL and I met problems when running "python setup.py install".

**Comment by huangs0** [comment]
I think it shall be supported, could you please kindly share me the error log (output of `python setup.py install`)?

**Comment by JLabandon** [comment]
Traceback (most recent call last):
  File "/mnt/d/neutrino/neutrino/neutrino/build.py", line 50, in <module>
    real_lib = os.readlink(loc)
               ^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '/usr/lib/wsl/lib/libcuda.so.1'

I was told by ChatGPT that this is due to the diffrence between WSL and native Linux.

**Comment by huangs0** [comment]
I [checked with WSL Github and it](https://github.com/microsoft/WSL/issues/5548) seems the point is WSL duplicates the `libcuda.so` rather than creating the symbolic link to `libcuda.so.1.1` (the real versioned name). 

Could you please kindly confirm this (by running `ls -l /usr/lib/wsl/lib/ | grep libcuda`)?

If so, I think a straightforward solution is check if this is a link or a real object in advance.

**Comment by B1fang** [comment]
Hey, the result of running command `ls -l /usr/lib/wsl/lib/ | grep libcuda` is:
```bash
-r-xr-xr-x 4 root root    171008 May 20 16:31 libcuda.so
-r-xr-xr-x 4 root root    171008 May 20 16:31 libcuda.so.1
-r-xr-xr-x 4 root root    171008 May 20 16:31 libcuda.so.1.1
-r-xr-xr-x 2 root root   9742088 May 20 16:31 libcudadebugger.so.1
```
on my WSL.
I solved the mentioned problem by modifying the code in `bulid.py`, line77 like:
```python
    # real_lib = os.readlink(loc)
    if os.path.islink(loc):  
        real_lib = os.readlink(loc)  
    else:    
        real_lib = os.path.basename(loc)
```
Then the problem solved and the neutrino successfully installed. However **I found another problem:** when I ran command like `neutrino -p block_sched python -c "import torch;torch.zeros((10, 10), dtype=torch.float64, device='cuda')"`(the case you gave in the paper), the `kernel` and `result` folder generated by neutrino is empty and the `event.log` file showed just like this:
```log
[init] pid 17441
[init] cmd 7 ./t_v1 
[init] dl 0x7f63739bb690
```
I've tried some cuda, Triton programs and the results are the same. So I guess on the WSL maybe the hook driver just not works well?
